<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_PaperMachine" Id="{4a8c14a2-6091-4cd1-afec-af3db8945cf3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PaperMachine
VAR_INPUT
	
	safetyCircuit		: BOOL;
	
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR


VAR_IN_OUT

	formingBoardSuctionRollDrive	: FB_DELTA_C2000_ETC;	
	formingBoardTractionRollDrive	: FB_DELTA_C2000_ETC;	

	stockPumpDrive	: FB_DELTA_C2000_ETC;	
	mixPumpDrive	: FB_DELTA_C2000_ETC;	
	wirePitPumpDrive	: FB_DELTA_C2000_ETC;	
	couchPitPumpDrive	: FB_DELTA_C2000_ETC;	

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_PaperMachine">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>