<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\PaperMachine.Historian.Application\PaperMachine.Historian.Application.csproj" />
    <ProjectReference Include="..\PaperMachine.Historian.Domain\PaperMachine.Historian.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Beckhoff.TwinCAT.Ads" Version="7.0.292" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
