<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\PaperMachine.Historian.Application\PaperMachine.Historian.Application.csproj" />
    <ProjectReference Include="..\PaperMachine.Historian.Domain\PaperMachine.Historian.Domain.csproj" />
    <ProjectReference Include="..\PaperMachine.Historian.Infrastructure.Ads\PaperMachine.Historian.Infrastructure.Ads.csproj" />
    <ProjectReference Include="..\PaperMachine.Historian.Infrastructure.Database\PaperMachine.Historian.Infrastructure.Database.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
    <PackageReference Include="OpenSans" Version="1.0.1" GeneratePathProperty="true" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.4" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="$(PkgOpenSans)\content\fonts\OpenSans\Regular\OpenSans-Regular.ttf" LogicalName="PaperMachine.Reporting.OpenSans-Regular.ttf" />
    <EmbeddedResource Include="$(PkgOpenSans)\content\fonts\OpenSans\Bold\OpenSans-Bold.ttf" LogicalName="PaperMachine.Reporting.OpenSans-Bold.ttf" />
    <EmbeddedResource Include="ReportingAssets\cpnteck-logo-black.png" LogicalName="PaperMachine.Reporting.CPNTeck-Logo.png" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>PaperMachine-Historian-9f44ca86-0676-4999-b2f8-a3230391eca8</UserSecretsId>
    <ClientAppDirectory>..\papermachine-web-client</ClientAppDirectory>
  </PropertyGroup>
  <Target Name="BuildClientForPublish" BeforeTargets="ComputeFilesToPublish" Condition="'$(SkipClientBuild)' != 'true'">
    <Exec WorkingDirectory="$(ClientAppDirectory)" Command="npm ci" />
    <Exec WorkingDirectory="$(ClientAppDirectory)" Command="npm run build" />
    <ItemGroup>
      <ClientDistFiles Include="wwwroot\**\*" />
      <ResolvedFileToPublish Include="@(ClientDistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>wwwroot\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
